#ifndef COMMONNETWORKCONST_H
#define COMMONNETWORKCONST_H

#define DISCOVERYSERVERPORT 45454
#define DISCOVERYCLIENTPORT 45455

#define DISCOVERYREQUEST "AreYouServer? "
#define DISCOVERYANSWER "YesIamServer! "

#endif // COMMONNETWORKCONST_H
